### PR TITLE
Handling Bad Requests

### PR DESCRIPTION
**Pull request by bobderrico80**
With the "happy paths" on the routes being close to being wrapped up, I wanted to start a discussion on handling API errors, rather than just committing, I'm creating a pull request so that we can have that discussion.

To start, I took the typical 400-Bad Request, if the required fields are not included in the body of POST and PUT requests.

To minimize code duplication, I created a new service `httpResponseService` to handle all response-related tasks. Right now, this service has two methods, `hasRequiredFields`, which returns true if the body has all required fields, and `getBadRequest` message, which creates a standard message to be passed through the HTTP response.

What do you think of this approach?

### CODE REVIEW

**Comment by Mac-lp3** [comment]
I am a bit new to selecting the perfect HTTP status so feel free to shoot me down.

I did a bit of research last night on S.O. about this and have been trying to stick with the convention of:

`GET, PUT,DELETE /resource/{id}` - Include a check to see if the resource exists in the code. If it does not, or if it is not assigned to the logged in user, return a 404 (resource not found).

Looking into the missing body params question now, I found two [possible](http://stackoverflow.com/questions/3050518/what-http-status-response-code-should-i-use-if-the-request-is-missing-a-required) [choices](http://stackoverflow.com/questions/6123425/rest-response-code-for-invalid-data):

400 - **(Bad Request) The request could not be understood by the server due to malformed syntax**. This seems to be the "catch all", as we could include a reason phrase to help the end user understand what happened.

422 - **(Unprocessable Entity) The server understands the content type of the request entity and the syntax of the request entity is correct but was unable to process the contained instructions**. We could go with this one for bad forms/missing input and reserve the 400 for more general server errors.

If the API is expected to become pretty complex, we may want to reserve the general 400 for when we need it most. Trying to be as specific as possible right now could save some refactor time in the future. Then again, if complexity stays moderate, I think we could get away with a 400 for all errors, and it might even make error handling easier on the front end (just check for the status code and extract the reason phrase).

Hope that helps.

**Comment by themightychris** [comment]
400 and 500 are generally status codes of last resort when there isn't a more specific code available

Another rule of thumb I like is that 4xx should all indicate that the given request should not be repeated as-is, whereas if it's a server issue and the client might have luck trying the same request again later you want a 5xx code

**Comment by themightychris** [comment]
As for keeping client code simple, the first digit is supposed to tell you overall what you need to know and then clients can optionally gain special handling for specific codes later

**Comment by bobderrico80** [comment]
Great points! In that case, for this PR, I think a 422 would make the most sense as @Mac-lp3 suggested.

**Pull request merged**
