### PR TITLE
Hash phone numbers in DB to make them harder to dump #97

### PR DESCRIPTION
**Pull request by wyantb**
Will put other comments related to security in https://github.com/yadaguru/yadaguru-app/issues/97 , but for some more technical bits:

Two notes:
* `SUPER_SECRET_SALT` should be an...actual secret, that only the app & admin knows about.  Storing it in plain text in the code is obviously silly :).  (And only serves to make sure that someone can't use an open set of hashes to test against our DB values; but with the salt in plain text like this they could still generate a collision table).  Any ideas on this one?  I'm assuming you have some idea how prod is configured, and therefore ideas on doing this.  (And obviously, losing the salt would be bad.  Don't do that ;)).
* This actually blows up the backend & prevents registration.  How long is the phoneNumber field allowed to be in `yadaguru-data`?  It probably needs to be a boatload longer if we store hashes

### CODE REVIEW

**Comment by bobderrico80** [comment]
`SUPER_SECRET_SALT` could be an environment variable, which would be configured on the server, and then accessed through `process.env.SUPER_SECRET_SALT`

Currently, I am logging directly into the server and setting env vars through the docker-compose file that I am using to deploy the stack. There is also a `SECRET` env var that is used to generate the access tokens? Could we use this value, or would it be better to have a separate secret for salting passwords.

I am doing some password salting in the admin user portal (though am probably not doing it right and could probably be improved):  https://github.com/yadaguru/yadaguru-data/blob/master/services/adminUserService.js

Regarding the field length for phoneNumber, that would probably need to be increased. I didn't explicity define a field length when I setup the models, so Sequelize probably chose one for me. When I am at my home laptop again, I'll double-check. We can create a migration.

**Comment by bobderrico80** [comment]
Double-checked the current schema... phoneNumber is `character varying(255)` currently. How long would we expect the hashed phone numbers to be?

**Comment by wyantb** [comment]
I'm paranoid, so I'd go with a separate SECRET_SALT environment variable; updated the code to accept that (and it blows up if not configured...I suppose we'd need to update the dev docker container to include one so that's not a setup step?)  

PS: for your code snippet, cool!  Didn't know there were APIs out there that bundled the salt with the records themselves.  That's cool, and while unintuitive when I first looked at it (since I know the basis of authentication is just checking equality of `hash(salt + password)`), really nifty.  I guess the only recommendation for the code you link, for more paranoia, would be a longer salt and to switch to `scrypt` ( https://www.npmjs.com/package/scrypt#api ) - it has an equivalent API and ( http://stackoverflow.com/a/5531194 ) is a lot more expensive to crack.  Really is almost no different to use:

```
var scryptParameters = scrypt.paramsSync(1);
var kdfResult = scrypt.kdfSync("password", scryptParameters);
```

**Comment by bobderrico80** [comment]
Regarding the combined salt, I am not sure it is best practice, but I did see it when looking up a tutorial to figure out how to do it. :-)

Thank you for the suggestion of scrypt. I am going to add a separate issue to the backlog to make the switch at some point.

I should be able to create a database migration to up the size of the phone number field to 512. 

What do you think would be the best way to handle existing phone numbers in the database that haven't been hashed? Fortunately, we aren't really in production yet, so there isn't too much harm if we lose them, but I know Michiko has set up a bunch of numbers in her testing environment, so it would be good if we can find a way to preserve them.

**Comment by wyantb** [comment]
Since we're not in production, we could pretty trivially add some code that, when a login occurs, first search for the phone number raw (assuming it matches the digit count, which it looks like you already validate), and if found by that path, updates itself on login.  Don't think we need to write a batch job or anything, just let the numbers handle themselves as Michiko tests stuff.

**Comment by bobderrico80** [comment]
Hey @wyantb, I've been playing around with this tonight. I managed to create a migration to increase the column size, and phone numbers are hashing as expected. :-)

However, is there a way we can decrypt the phone number internally? We will need access to the user's phone numbers in order to send SMS messages. I looked through the documentation, but didn't see a clear answer. Hoping you can shed some light. Thanks!!

**Comment by wyantb** [comment]
Ah, I didn't think of that.  one-way hashing algorithms are...just that,
not designed to be able to invert like this.

Only thing we can do is use a encryption / decryption approach with the
secret, then.  With a hash if someone gets the salt they still have to
generate collisions which takes computation; with an enc/dec approach they
have all the numbers right away.

No other choice though.  I can look at switching the next time I do a burst
of work on the project.

Brian Wyant (Phone)

**Comment by wyantb** [comment]
Oh, and: where is the texting done?  Somewhere in API?  I didn't notice the
codepath at the time to think of it.

Brian Wyant (Phone)

**Comment by bobderrico80** [comment]
I think we will be okay with just encryption/decryption. We are not storing any other information aside from the phone number, so if someone were to get access to the DB as well as the secret, they would just have a list of phone numbers.

You are correct that when you did this work that there were no references to the phone number. I recently added an endpoint to send the user a text message after they complete onboarding (this is in the usersController.js). Also the yadaguru-sms repo uses the phone number stored in the db to send the daily batch of text messages.

**Comment by bobderrico80** [comment]
Created PR in the yadaguru-data project to handle phone number encryption/decryption: https://github.com/yadaguru/yadaguru-data/pull/5

**Pull request closed without merging**
